/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.laptrinhjava.chuong03.dohoa.frames;

import com.mycompany.laptrinhjava.chuong03.coffeelogic.CoffeeShop;
import com.mycompany.laptrinhjava.chuong03.coffeelogic.Manager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class MyCoffee extends javax.swing.JInternalFrame {
    
    
     Manager[] QuanLy;
    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
         SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        CoffeeShop[] a = new CoffeeShop[]{new CoffeeShop("Gong cha", "Nguyen Hue"),
                                          new CoffeeShop("Tan Coffee", "Nguyen Thi Minh Khai")};
        QuanLy = new Manager[]{ new Manager(a, 1000, "Nguyen Van B", 0, df.parse("12-10-2001")),
                           new Manager(new CoffeeShop[]{
                                      new CoffeeShop("Ca Map Con", "To Huu")}, 0, "Phan Van A", 0, df.parse("20-12-2001"))
                                   
                              };
        for(int i = 0; i< QuanLy.length; i ++){
            cbQuanLy.addItem(QuanLy[i].getHoTen());
        }
        
        DefaultTableModel model = (DefaultTableModel) tbCoffeeShop.getModel();
        model.setRowCount(0);
        CoffeeShop[] Shops = QuanLy[0].getShopcf();
        for(int i = 0; i< Shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() +1,Shops[i].getName(), Shops[i].getAddress()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbQuanLy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCoffeeShop = new javax.swing.JTable();

        setTitle("Danh Sách quản lý quán cafe");

        jLabel1.setText("Họ tên người quản lý");

        cbQuanLy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQuanLyItemStateChanged(evt);
            }
        });

        tbCoffeeShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Quán", "Địa Chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbCoffeeShop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(cbQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQuanLy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbQuanLyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQuanLyItemStateChanged
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tbCoffeeShop.getModel();
        model.setRowCount(0);
        int index = cbQuanLy.getSelectedIndex();
        CoffeeShop[] Shops = QuanLy[index].getShopcf();
        for(int i = 0; i< Shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() +1,Shops[i].getName(), Shops[i].getAddress()});
            
        }
        
    }//GEN-LAST:event_cbQuanLyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbQuanLy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCoffeeShop;
    // End of variables declaration//GEN-END:variables
}
